name: rule-net
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - jupyterlab==4.4.3
    - requests==2.32.5
    - numpy==2.2.6
    - pandas==2.3.2
    - matplotlib==3.10.6
    - tqdm==4.67.1
    - pytest==8.4.2
    - sympy==1.14.0
    - wittgenstein==0.3.4
    - scikit-learn==1.7.2
    - networkx==3.4.2